### ISSUE TITLE
Publish type hints - Make tecton PEP561 compatible

### ISSUE THREAD

**Issue by torstenrudolf** [tecton-ai/tecton-http-client-python#60]
I see this code-base makes use of python type hints.
Unfortunately it seems to not export those. When running `mypy` on my project I get:

```
error: Skipping analyzing "tecton": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```

I couldn't find a `types-tecton` package so I assume currently the types are not published.

A simple solution could be to add an empty `py.typed` file to the source-root, as described in the [mypy docs](https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages).

### Please describe your feature request:
Publish tecton type-hints, so projects using this package can get better `mypy` coverage.

**Comment by solbrigm** [comment]
Adding py.typed file here: https://github.com/tecton-ai/tecton-http-client-python/pull/59
